### ISSUE TITLE
[BUG]: Color-coding of x-Position and y-Position labels are reversed

### ISSUE THREAD

**Issue by tpsherrill** [jneilliii/OctoPrint-BedLevelVisualizer#301] opened 2020-09-24 14:43 UTC
**Describe the bug**
The labels on the Current Mesh Data and Angle Corrections tabs show the x and y axis labels switched. My understanding is that the XY coordinates are standard (x along the bottom, y going up the left edge). The color coding shows the bottom axis as 'y - Position' and the vertical axis the 'x - Position'
![image](https://user-images.githubusercontent.com/58983922/94160392-90e63200-fe52-11ea-976e-0d46c378fb77.png)

The CSS class on the vertical and horizontal axis labels should be reversed. The vertical axis is getting the x-axis-label class.
css: x-axis-label, y-axis-label
![image](https://user-images.githubusercontent.com/58983922/94160348-86c43380-fe52-11ea-9ed1-54a0a4757eb2.png)

**Expected behavior**
The bold/black and bold/green coloring on the labels should be switched.

**Debug Log**

**Screenshots**

**Firmware and Version**

**Comment by tpsherrill** [comment] 2020-09-24 14:47
As a new user to mesh bed leveling, this was very difficult to get my head around since the labels were backwards. With different printers using different origin strategies/home locations and the somewhat cryptic marlin output from the mesh levels in terminal, I struggled to follow what was happening. I think I have figured this out experimentally...

There may be another related issue with the buttons in the settings for 'Flip X Axis' and 'Flip Y Axis'

If this isn't an issue, then I need an orientation on how to read the table. Thanks for your great plugin!

**Comment by jneilliii** [comment] 2020-09-24 18:00
This is actually a duplicate of #278 and has already been resolved in my current development branch.

**Comment by tpsherrill** [comment] 2020-09-24 20:21
Good to know. I reviewed the open issues before posting. Did you catch the issue with the item I mentioned in the comment?
_There may be another related issue with the buttons in the settings for 'Flip X Axis' and 'Flip Y Axis'_
I believe they are also reversed.

**Comment by jneilliii** [comment] 2020-09-24 20:37
There's two different flip options, one in the correction area ans one in the normal area, related to how the data is collected. The ones in the first tab should have no effect on the corrections.

**Comment by jneilliii** [comment] 2020-10-03 04:04
fixed the label colors in version 0.1.15

**Closed as completed by jneilliii** 2020-10-03 04:04 UTC
