### ISSUE TITLE
[FR]: Probe more points than just 9

### ISSUE THREAD

**Issue by twiclo** [jneilliii/OctoPrint-BedLevelVisualizer#406] opened 2021-03-17 00:35 UTC
I'd like to see this capable of printing more than just 9 points please. If this is already a feature somewhere I don't see where

**Comment by jneilliii** [comment] 2021-03-17 04:09
duplicate of #370 #378 I don't control how many points your firmware probes for auto bed leveling, this plugin just visualizes what is available from the firmware.

**Closed as completed by jneilliii** 2021-03-17 04:09 UTC
Labels: duplicate
