### ISSUE TITLE
Side effect of update, please fix [FR]: 

### ISSUE THREAD

**Issue by BitRacer** [jneilliii/OctoPrint-BedLevelVisualizer#284] opened 2020-08-18 01:09 UTC
**Is your feature request related to a problem? Please describe.**

The new way of setting the colors for the visualization results in the z axis being static
**Describe the solution you'd like**

I prefer the old behavior where the z axis was dynamic.  I was able to get my leveling down to 0.01mm this way
**Describe alternatives you've considered**

Please put the dynamic z axis back.  Allowing users to choose colors is nice, but not the z axis.  I would recommend you simply divide the space evenly between the colors provided, but still keep the z axis dynamic
**Additional context**

**Comment by jneilliii** [comment] 2020-08-18 03:36
Duplicate of #275 I have a development branch that adds the option for `auto`.

**Closed as completed by jneilliii** 2020-08-18 03:36 UTC
