### ISSUE TITLE
[FR]: Export Mesh Values

### ISSUE THREAD

**Issue by ademolay2000** [jneilliii/OctoPrint-BedLevelVisualizer#551] opened 2022-06-25 19:35 UTC
This may already be in here, but the ability to export mesh values directly from the visualizer would be handy (i.e. CSV).  There are times when I'd like to compare the values between runs, and dropping them into Excel would be great.

**Comment by jneilliii** [comment] 2022-06-26 03:42
You might want to try my companion plugin that allows you to switch through previous runs.

https://github.com/jneilliii/OctoPrint-BLVLogger

**Comment by jneilliii** [comment] 2022-06-26 03:44
going to mark this as duplicate of #329

**Closed as completed by jneilliii** 2022-06-26 03:44 UTC
Labels: duplicate

**Comment by ademolay2000** [comment] 2022-06-26 17:35
I'm after the raw data for manipulation.  Does BLV store that anywhere accessible to laymen?

**Comment by jneilliii** [comment] 2022-06-26 17:55
Bed Level Visualizer does not, BLV Logger plugin linked above saves the data to sqllite database on the server.
