### ISSUE TITLE
Updating Mesh deletes custom controls from config.yaml

### ISSUE THREAD

**Issue by shelbyRobots** [jneilliii/OctoPrint-BedLevelVisualizer#244] opened 2020-05-13 23:13 UTC
When the new mesh is saved in config.yaml after pressing "Update Mesh Now", all of the controls: section gets deleted.  This includes things generated manually or via the custom controls plugin.

**Comment by jneilliii** [comment] 2020-05-14 00:07
Duplicate of #228

**Closed as completed by jneilliii** 2020-05-14 00:07 UTC
