### ISSUE TITLE
[BUG]: Plugin not present after sucessfull install

### ISSUE THREAD

**Issue by ahorvat** [jneilliii/OctoPrint-BedLevelVisualizer#283] opened 2020-08-15 02:07 UTC
**Describe the bug**
After installing the plugin and receiving a success message, the plugin is not present after performing the requested reboot. I have attempted install several times using the Plugin Mangager and additionaly also through CLI, both yield the same result.=

**Debug Log**

(venv) octo@bpi-iot-ros-ai:~ $ pip install "https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip
  Downloading https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip
     | 2.7 MB 5.1 MB/s
Requirement already satisfied (use --upgrade to upgrade): Bed-Visualizer==0.1.14 from https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip in ./venv/lib/python3.7/site-packages
Requirement already satisfied: OctoPrint in ./venv/lib/python3.7/site-packages (from Bed-Visualizer==0.1.14) (1.4.2)
Requirement already satisfied: numpy in ./venv/lib/python3.7/site-packages (from Bed-Visualizer==0.1.14) (1.19.1)
Requirement already satisfied: cachelib<1,>=0.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.1.1)
Requirement already satisfied: pylru<2,>=1.2 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.2.0)
Requirement already satisfied: blinker<2,>=1.4 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.4)
Requirement already satisfied: netifaces<1,>=0.10.9 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.10.9)
Requirement already satisfied: wrapt<2,>=1.12.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.12.1)
Requirement already satisfied: requests<3,>=2.23.0 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (2.24.0)
Requirement already satisfied: markdown<3.2,>=3.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (3.1.1)
Requirement already satisfied: psutil<6,>=5.7 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (5.7.2)
Requirement already satisfied: sarge==0.1.5post0 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.1.5.post0)
Requirement already satisfied: Flask-Assets<3,>=2.0 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (2.0)
Requirement already satisfied: Click<8,>=7.1.2 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (7.1.2)
Requirement already satisfied: pyserial<4,>=3.4 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (3.4)
Requirement already satisfied: netaddr<1,>=0.7.19 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.7.20)
Requirement already satisfied: websocket-client<1,>=0.57 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.57.0)
Requirement already satisfied: Jinja2<3,>=2.11.2 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (2.11.2)
Requirement already satisfied: Flask-Babel<2,>=1.0 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.0.0)
Requirement already satisfied: regex!=2018.11.6 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (2020.7.14)
Requirement already satisfied: frozendict<2,>=1.2 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.2)
Requirement already satisfied: watchdog<1,>=0.10.2 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.10.3)
Requirement already satisfied: tornado==5.1.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (5.1.1)
Requirement already satisfied: PyYAML<6,>=5.3.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (5.3.1)
Requirement already satisfied: OctoPrint-FileCheck>=2020.07.06 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (2020.8.7)
Requirement already satisfied: rsa==4.0 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (4.0)
Requirement already satisfied: flask<2,>=1.1.2 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.1.2)
Requirement already satisfied: unidecode<0.05,>=0.04.14 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.4.21)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.1.0)
Requirement already satisfied: pkginfo<2,>=1.5.0.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.5.0.1)
Requirement already satisfied: werkzeug<2,>=1.0.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.0.1)
Requirement already satisfied: markupsafe<2.0,>=1.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.1.1)
Requirement already satisfied: filetype<2,>=1.0.7 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (1.0.7)
Requirement already satisfied: emoji<1,>=0.5.4 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.5.4)
Requirement already satisfied: feedparser<6,>=5.2.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (5.2.1)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2020.06.22 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (2020.6.22)
Requirement already satisfied: semantic-version<3,>=2.8.5 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (2.8.5)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.5.0)
Requirement already satisfied: future<1,>=0.18.2 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.18.2)
Requirement already satisfied: sentry-sdk<1,>=0.15.1 in ./venv/lib/python3.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.14) (0.16.3)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->Bed-Visualizer==0.1.14) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->Bed-Visualizer==0.1.14) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->Bed-Visualizer==0.1.14) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->Bed-Visualizer==0.1.14) (1.25.10)
Requirement already satisfied: setuptools>=36 in ./venv/lib/python3.7/site-packages (from markdown<3.2,>=3.1->OctoPrint->Bed-Visualizer==0.1.14) (49.2.1)
Requirement already satisfied: webassets>=2.0 in ./venv/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->Bed-Visualizer==0.1.14) (2.0)
Requirement already satisfied: six in ./venv/lib/python3.7/site-packages (from websocket-client<1,>=0.57->OctoPrint->Bed-Visualizer==0.1.14) (1.15.0)
Requirement already satisfied: Babel>=2.3 in ./venv/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->Bed-Visualizer==0.1.14) (2.8.0)
Requirement already satisfied: pytz in ./venv/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->Bed-Visualizer==0.1.14) (2020.1)
Requirement already satisfied: pathtools>=0.1.1 in ./venv/lib/python3.7/site-packages (from watchdog<1,>=0.10.2->OctoPrint->Bed-Visualizer==0.1.14) (0.1.2)
Requirement already satisfied: pyasn1>=0.1.3 in ./venv/lib/python3.7/site-packages (from rsa==4.0->OctoPrint->Bed-Visualizer==0.1.14) (0.4.8)
Building wheels for collected packages: Bed-Visualizer
  Building wheel for Bed-Visualizer (setup.py) ... done
  Created wheel for Bed-Visualizer: filename=Bed_Visualizer-0.1.14-py3-none-any.whl size=2549304 sha256=34d1db001196ec24b3af3992add70ff255e70d488494b58cb6b17d33539d65e0
  Stored in directory: /tmp/pip-ephem-wheel-cache-cl_zgocq/wheels/75/44/35/74bcf9f68ddaab8d67a995ba5a7e3046f91b4d7169880d062e
Successfully built Bed-Visualizer

Version:
Octoprint: Version 1.4.2
Python: Version 3.7.4

**Comment by jneilliii** [comment] 2020-08-15 14:23
Duplicate of #213

**Closed as completed by jneilliii** 2020-08-15 14:23 UTC
