### ISSUE TITLE
[BUG]: Floating point error

### ISSUE THREAD

**Issue by C0rn3j** [jneilliii/OctoPrint-BedLevelVisualizer#514] opened 2022-01-18 13:47 UTC
![image](https://user-images.githubusercontent.com/1641362/149949058-80c7e1ca-417f-43f2-be61-110b627eed47.png)

You can see the floating point error in Var value, this is the first time I am seeing it after about 20 levelings, so I assume reproducing it is hard.

```js
Bed Visualizer Settings Version 1.1.1
octoprint 1.7.2
python 3.10.1
```

**Comment by jneilliii** [comment] 2022-01-18 16:46
Actually it's not difficult. Other people have reported the same, duplicate of #499

**Closed as completed by jneilliii** 2022-01-18 16:46 UTC
