### ISSUE TITLE
Y axis in plotted view is inverted.

### ISSUE THREAD

**Issue by Swesen** [jneilliii/OctoPrint-BedLevelVisualizer#43] opened 2018-04-26 16:12 UTC
The Y axis is inverted in version 0.0.8 that I just updated to.

This is from G29 T0 to get the bounding box numbers.
![](https://i.gyazo.com/ab9671897ea25a674f43a6f5441096ee.png)
As you can see point X10, Y10 is -0.384 which should ge at X10, Y260 for example.
![](https://i.gyazo.com/585645124bdbef553f6381716191b0b8.png)

Maybe a setting to invert X and Y if some firmwares plot it differently.

**Comment by jneilliii** [comment] 2018-04-26 17:01
Duplicate of #40.

**Closed as completed by jneilliii** 2018-04-26 17:01 UTC
