### ISSUE TITLE
[BUG]: no downgrade at release channel change

### ISSUE THREAD

**Issue by electronicm** [jneilliii/OctoPrint-BedLevelVisualizer#472] opened 2021-09-18 20:30 UTC
**Describe the bug**
When I change the release channel from "Release Candidate" back to "Stable", I do not get a downgrade.
I have to uninstall and reinstall the plug in.

**Expected behavior**
When I change the release channel, as with various other plugins and also OctoPrint itself, the current version of the channel should be installed.

**Comment by jneilliii** [comment] 2021-09-18 23:37
This should work like the others, Are there any errors in octoprint.log or plugin_bedlevelvisualizer_debug.log file?

**Comment by jneilliii** [comment] 2021-09-19 01:40
confirmed reproducible

**Comment by jneilliii** [comment] 2021-09-19 17:31
I believe this to be an upstream bug and have created the above issue in OctoPrint's repo to track.

**Comment by jneilliii** [comment] 2022-01-01 08:31
Since this appears to be resolved upstream and will be release in the next version of OctoPrint closing issue.

**Closed as completed by jneilliii** 2022-01-01 08:31 UTC
Labels: bug
