### ISSUE TITLE
[FR]: importing Data for processing

### ISSUE THREAD

**Issue by stonegrift** [jneilliii/OctoPrint-BedLevelVisualizer#483] opened 2021-10-29 18:46 UTC
**Is your feature request related to a problem? Please describe.**
Reprap doesn't seem to report data with G29 T command. Data is reported by G33 L0. 

**Describe the solution you'd like**
The ability to parse G33 L0 data

**Describe alternatives you've considered**
It would be nice to be able to go into the terminal and copy the reported data into the plugin manually to be displayed to help with bed leveling.  Perhaps as a CSV cut and paste.  That could be edited for the format needed.

**Additional context**
An example of the reported data with G33 L0
Recv: G33 X-86.00 Y-86.00 Z0.088
Recv: G33 X-86.00 Y-43.00 Z-0.100
Recv: G33 X-86.00 Y0.00 Z0.100
Recv: G33 X-86.00 Y43.00 Z0.113
Recv: G33 X-86.00 Y86.00 Z0.213
Recv: G33 X-43.00 Y-86.00 Z0.725
Recv: G33 X-43.00 Y-43.00 Z0.875
Recv: G33 X-43.00 Y0.00 Z0.688
Recv: G33 X-43.00 Y43.00 Z0.375
Recv: G33 X-43.00 Y86.00 Z0.187
Recv: G33 X0.00 Y-86.00 Z0.963
Recv: G33 X0.00 Y-43.00 Z0.963
Recv: G33 X0.00 Y0.00 Z0.638
Recv: G33 X0.00 Y43.00 Z0.263
Recv: G33 X0.00 Y86.00 Z0.075
Recv: G33 X43.00 Y-86.00 Z0.713
Recv: G33 X43.00 Y-43.00 Z0.600
Recv: G33 X43.00 Y0.00 Z0.237
Recv: G33 X43.00 Y43.00 Z-0.012
Recv: G33 X43.00 Y86.00 Z0.000
Recv: G33 X86.00 Y-86.00 Z0.312
Recv: G33 X86.00 Y-43.00 Z-0.063
Recv: G33 X86.00 Y0.00 Z-0.300
Recv: G33 X86.00 Y43.00 Z-0.250
Recv: G33 X86.00 Y86.00 Z-0.137

**Comment by jneilliii** [comment] 2021-10-29 19:25
kind of a duplicate of #329. this comment will link that FR and I'll account for it there for repetier.

**Closed as completed by jneilliii** 2021-10-29 19:25 UTC
Labels: duplicate, enhancement
