### ISSUE TITLE
[FR]: Different colours for data labels

### ISSUE THREAD

**Issue by scott-ish** [jneilliii/OctoPrint-BedLevelVisualizer#636] opened 2023-10-27 14:28 UTC
**Is your feature request related to a problem? Please describe.**
I find it hard to read the data labels in blue and red especially in dark mode.

**Describe the solution you'd like**
The option to change these colours or set them to white.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by jneilliii** [comment] 2023-10-27 15:31
duplicate of #634

**Closed as completed by jneilliii** 2023-10-27 15:31 UTC
Labels: duplicate
